/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela_Inicial;

import Cadastro_carro.Cadastro_carro_tela;
import Cadastro_cliente.Cadastro_cliente;
import Cadastro_fornecedor.Cadastro_Fornecedor;
import Cadastro_funcionario.Frame_Cadastro_Funcionario;
import Cadastro_pecas_lotes.Cadastro_pecas_lotes;
import Cadastro_pedidos.Cadastro_pedidos;
import Ordem_Servico.Ordem_Servico;
import Tela_estoque.Tela_estoque;
import Tela_mapa.Tela_Mapa_Kevin;

/**
 *
 * @author farne
 */
public class Tela_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal_002
     */
    public Tela_Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Filtro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDA_cadastro_carrro = new javax.swing.JButton();
        IDA_cadastro_funcionario = new javax.swing.JButton();
        IDA_cadastro_pedidos = new javax.swing.JButton();
        IDA_ordemServiço = new javax.swing.JButton();
        IDA_cadastro_cliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Filtragem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Filtragem_funcionario = new javax.swing.JRadioButton();
        Filtragem_fornecedor = new javax.swing.JRadioButton();
        Filtragem_Peca = new javax.swing.JRadioButton();
        Filtragem_cliente = new javax.swing.JRadioButton();
        Filtragem_carro = new javax.swing.JRadioButton();
        Filtragem_pedido = new javax.swing.JRadioButton();
        IDA_login = new javax.swing.JButton();
        IDA_mapaestoque = new javax.swing.JButton();
        IDA_cadastro_pecas = new javax.swing.JButton();
        IDA_estoque = new javax.swing.JButton();
        IDA_cadastro_fornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Principal");

        IDA_cadastro_carrro.setText("Cadastro de carros");
        IDA_cadastro_carrro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_cadastro_carrroActionPerformed(evt);
            }
        });

        IDA_cadastro_funcionario.setText("Cadastro de funcionário");
        IDA_cadastro_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_cadastro_funcionarioActionPerformed(evt);
            }
        });

        IDA_cadastro_pedidos.setText("Cadastro de pedidos");
        IDA_cadastro_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_cadastro_pedidosActionPerformed(evt);
            }
        });

        IDA_ordemServiço.setText("Ordem de serviço");
        IDA_ordemServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_ordemServiçoActionPerformed(evt);
            }
        });

        IDA_cadastro_cliente.setText("Cadastro de cliente");
        IDA_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_cadastro_clienteActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel2.setBackground(new java.awt.Color(75, 75, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pesquisa");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 6, -1, -1));

        jButton6.setText("Pesquisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        Filtragem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Filtragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiltragemMouseClicked(evt);
            }
        });
        jPanel2.add(Filtragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 60, 630, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Filtro.add(Filtragem_funcionario);
        Filtragem_funcionario.setForeground(new java.awt.Color(255, 255, 255));
        Filtragem_funcionario.setText("Funcionario");
        Filtragem_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtragem_funcionarioActionPerformed(evt);
            }
        });
        jPanel2.add(Filtragem_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        Filtro.add(Filtragem_fornecedor);
        Filtragem_fornecedor.setForeground(new java.awt.Color(255, 255, 255));
        Filtragem_fornecedor.setText("Fornecedor");
        Filtragem_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtragem_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(Filtragem_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        Filtro.add(Filtragem_Peca);
        Filtragem_Peca.setForeground(new java.awt.Color(255, 255, 255));
        Filtragem_Peca.setText("Peça");
        Filtragem_Peca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtragem_PecaActionPerformed(evt);
            }
        });
        jPanel2.add(Filtragem_Peca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        Filtro.add(Filtragem_cliente);
        Filtragem_cliente.setForeground(new java.awt.Color(255, 255, 255));
        Filtragem_cliente.setText("Cliente");
        Filtragem_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtragem_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(Filtragem_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        Filtro.add(Filtragem_carro);
        Filtragem_carro.setForeground(new java.awt.Color(255, 255, 255));
        Filtragem_carro.setText("Carro");
        Filtragem_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtragem_carroActionPerformed(evt);
            }
        });
        jPanel2.add(Filtragem_carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        Filtro.add(Filtragem_pedido);
        Filtragem_pedido.setForeground(new java.awt.Color(255, 255, 255));
        Filtragem_pedido.setText("Pedido");
        Filtragem_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtragem_pedidoActionPerformed(evt);
            }
        });
        jPanel2.add(Filtragem_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        IDA_login.setText("Sair");
        IDA_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_loginActionPerformed(evt);
            }
        });

        IDA_mapaestoque.setText("Mapa do esoque");
        IDA_mapaestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_mapaestoqueActionPerformed(evt);
            }
        });

        IDA_cadastro_pecas.setText("Cadastro de peças");
        IDA_cadastro_pecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_cadastro_pecasActionPerformed(evt);
            }
        });

        IDA_estoque.setText("Estoque");
        IDA_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_estoqueActionPerformed(evt);
            }
        });

        IDA_cadastro_fornecedor.setText("Cadastro de fornecedor");
        IDA_cadastro_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDA_cadastro_fornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(IDA_cadastro_fornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDA_cadastro_pedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDA_cadastro_funcionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(IDA_login, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IDA_cadastro_carrro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDA_cadastro_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDA_mapaestoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDA_cadastro_pecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDA_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(IDA_ordemServiço, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(IDA_cadastro_carrro)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_cadastro_funcionario)
                        .addGap(20, 20, 20)
                        .addComponent(IDA_cadastro_pedidos)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_cadastro_cliente)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_cadastro_pecas)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_cadastro_fornecedor)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_ordemServiço)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_estoque)
                        .addGap(18, 18, 18)
                        .addComponent(IDA_mapaestoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDA_login))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDA_cadastro_carrroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_cadastro_carrroActionPerformed
        // TODO add your handling code here:
        Cadastro_carro_tela cadCar = new Cadastro_carro_tela();
        cadCar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_cadastro_carrroActionPerformed

    private void IDA_cadastro_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_cadastro_funcionarioActionPerformed
        // TODO add your handling code here:
        Frame_Cadastro_Funcionario cadFunc = new Frame_Cadastro_Funcionario();
        cadFunc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_cadastro_funcionarioActionPerformed

    private void IDA_cadastro_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_cadastro_pedidosActionPerformed
        // TODO add your handling code here:
        Cadastro_pedidos cadPed = new Cadastro_pedidos();
        cadPed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_cadastro_pedidosActionPerformed

    private void IDA_ordemServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_ordemServiçoActionPerformed
        // TODO add your handling code here:
        Ordem_Servico ordServ = new Ordem_Servico();
        ordServ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_ordemServiçoActionPerformed

    private void IDA_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_cadastro_clienteActionPerformed
        // TODO add your handling code here:
        Cadastro_cliente cadCli = new Cadastro_cliente();
        cadCli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_cadastro_clienteActionPerformed

    private void IDA_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_loginActionPerformed
        // TODO add your handling code here:
        Tela_login_Concluida ifaLog = new Tela_login_Concluida();
        ifaLog.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_IDA_loginActionPerformed

    private void IDA_mapaestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_mapaestoqueActionPerformed
        Tela_Mapa_Kevin TMap = new Tela_Mapa_Kevin();
        TMap.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_IDA_mapaestoqueActionPerformed

    private void IDA_cadastro_pecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_cadastro_pecasActionPerformed
        // TODO add your handling code here:
        Cadastro_pecas_lotes cadPeca = new Cadastro_pecas_lotes();
        cadPeca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_cadastro_pecasActionPerformed

    private void IDA_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_estoqueActionPerformed
        // TODO add your handling code here:
        Tela_estoque estoque = new Tela_estoque();
        estoque.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_estoqueActionPerformed

    private void IDA_cadastro_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDA_cadastro_fornecedorActionPerformed
        // TODO add your handling code here:
        Cadastro_Fornecedor cadFor = new Cadastro_Fornecedor();
        cadFor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IDA_cadastro_fornecedorActionPerformed

    private void FiltragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiltragemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltragemMouseClicked

    public int escolhaFiltragem;
    
    private void Filtragem_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtragem_funcionarioActionPerformed
        // TODO add your handling code here:
        escolhaFiltragem = 1;
    }//GEN-LAST:event_Filtragem_funcionarioActionPerformed

    private void Filtragem_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtragem_fornecedorActionPerformed
        // TODO add your handling code here:
        escolhaFiltragem = 3;
    }//GEN-LAST:event_Filtragem_fornecedorActionPerformed

    private void Filtragem_PecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtragem_PecaActionPerformed
        // TODO add your handling code here:
        escolhaFiltragem = 5;
    }//GEN-LAST:event_Filtragem_PecaActionPerformed

    private void Filtragem_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtragem_clienteActionPerformed
        // TODO add your handling code here:
        escolhaFiltragem = 2;
    }//GEN-LAST:event_Filtragem_clienteActionPerformed

    private void Filtragem_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtragem_carroActionPerformed
        // TODO add your handling code here:
        escolhaFiltragem = 4;
    }//GEN-LAST:event_Filtragem_carroActionPerformed

    private void Filtragem_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtragem_pedidoActionPerformed
        // TODO add your handling code here:
        escolhaFiltragem = 6;
    }//GEN-LAST:event_Filtragem_pedidoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String pesquisa = Filtragem.getText();
        switch(escolhaFiltragem){
            case 1:
                tabelaFuncionario tabFun = new tabelaFuncionario();
                tabFun.setValores(pesquisa);
                tabFun.setVisible(true);
                this.dispose();
                break;
            case 2:
                tabelaCliente tabCli = new tabelaCliente();
                tabCli.setValores(pesquisa);
                tabCli.setVisible(true);
                this.dispose();
                break;
            case 3:
                tabelaFornecedor tabFor = new tabelaFornecedor();
                tabFor.setValores(pesquisa);
                tabFor.setVisible(true);
                this.dispose();
                break;
            case 4:
                tabelaCarro tabCar = new tabelaCarro();
                tabCar.setValores(pesquisa);
                tabCar.setVisible(true);
                this.dispose();
                break;
            case 5:
                tabelaPeca tabPeca = new tabelaPeca();
                tabPeca.setValores(pesquisa);
                tabPeca.setVisible(true);
                this.dispose();
                break;
            case 6:
                tabelaPedido tabPed = new tabelaPedido();
                tabPed.setValores(pesquisa);
                tabPed.setVisible(true);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Filtragem;
    private javax.swing.JRadioButton Filtragem_Peca;
    private javax.swing.JRadioButton Filtragem_carro;
    private javax.swing.JRadioButton Filtragem_cliente;
    private javax.swing.JRadioButton Filtragem_fornecedor;
    private javax.swing.JRadioButton Filtragem_funcionario;
    private javax.swing.JRadioButton Filtragem_pedido;
    private javax.swing.ButtonGroup Filtro;
    private javax.swing.JButton IDA_cadastro_carrro;
    private javax.swing.JButton IDA_cadastro_cliente;
    private javax.swing.JButton IDA_cadastro_fornecedor;
    private javax.swing.JButton IDA_cadastro_funcionario;
    private javax.swing.JButton IDA_cadastro_pecas;
    private javax.swing.JButton IDA_cadastro_pedidos;
    private javax.swing.JButton IDA_estoque;
    private javax.swing.JButton IDA_login;
    private javax.swing.JButton IDA_mapaestoque;
    private javax.swing.JButton IDA_ordemServiço;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
