/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cadastro_cliente;

import Tela_inicial_LianHenrique.Tela_inicial_LianHenrique;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class Cadastro_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_cliente
     */
    public Cadastro_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_background = new javax.swing.JPanel();
        jlbl_title_cadastro_cliente = new javax.swing.JLabel();
        jlbl_nome = new javax.swing.JLabel();
        jlbl_telefone = new javax.swing.JLabel();
        jlbl_email = new javax.swing.JLabel();
        jfield_nome_cliente = new javax.swing.JTextField();
        jfield_telefone_cliente = new javax.swing.JTextField();
        jfield_email_cliente = new javax.swing.JTextField();
        jbutton_sair = new javax.swing.JButton();
        jbutton_cadastrar = new javax.swing.JButton();
        jlbl_cpf = new javax.swing.JLabel();
        jfield_cpf_cliente = new javax.swing.JTextField();
        jlbl_data_nascimento = new javax.swing.JLabel();
        jfield_data_nascimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_background.setBackground(new java.awt.Color(46, 46, 46));
        jpanel_background.setPreferredSize(new java.awt.Dimension(1036, 612));
        jpanel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_title_cadastro_cliente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlbl_title_cadastro_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_title_cadastro_cliente.setText("Cadastro de cliente");
        jpanel_background.add(jlbl_title_cadastro_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jlbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_nome.setText("Nome:");
        jpanel_background.add(jlbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jlbl_telefone.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_telefone.setText("Telefone:");
        jpanel_background.add(jlbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jlbl_email.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_email.setText("E-mail:");
        jpanel_background.add(jlbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));
        jpanel_background.add(jfield_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 600, 30));
        jpanel_background.add(jfield_telefone_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 600, 30));

        jfield_email_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_email_clienteActionPerformed(evt);
            }
        });
        jpanel_background.add(jfield_email_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 600, 30));

        jbutton_sair.setText("Sair");
        jbutton_sair.setPreferredSize(new java.awt.Dimension(70, 25));
        jbutton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_sairActionPerformed(evt);
            }
        });
        jpanel_background.add(jbutton_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 90, -1));

        jbutton_cadastrar.setText("Cadastrar");
        jbutton_cadastrar.setPreferredSize(new java.awt.Dimension(70, 25));
        jbutton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_cadastrarActionPerformed(evt);
            }
        });
        jpanel_background.add(jbutton_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 90, -1));

        jlbl_cpf.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_cpf.setText("CPF:");
        jpanel_background.add(jlbl_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jfield_cpf_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cpf_clienteActionPerformed(evt);
            }
        });
        jpanel_background.add(jfield_cpf_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 600, 30));

        jlbl_data_nascimento.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_data_nascimento.setText("Data de Nascimento:");
        jpanel_background.add(jlbl_data_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jfield_data_nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_data_nascimentoActionPerformed(evt);
            }
        });
        jpanel_background.add(jfield_data_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 600, 30));

        getContentPane().add(jpanel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_sairActionPerformed
        // TODO add your handling code here:
        Tela_inicial_LianHenrique tela_inicial = new Tela_inicial_LianHenrique();
        tela_inicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbutton_sairActionPerformed

    private void jbutton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_cadastrarActionPerformed
        // TODO add your handling code here:
        String nome;
        String email;
        String cpf;
        String telefone;
   
        boolean nome_valido;
        boolean email_valido;
        boolean cpf_valido;
        boolean telefone_valido;
        
        nome = jfield_nome_cliente.getText();
        email = jfield_email_cliente.getText();
        cpf = jfield_cpf_cliente.getText();
        telefone = jfield_telefone_cliente.getText();
        
        nome_valido = validador_entrada_str(nome, 50);
        email_valido = validador_tamanho_texto(email, 50);
        cpf_valido = validador_entrada_num(cpf, 11);
        telefone_valido = validador_entrada_num(telefone, 9);
        
        if (nome_valido && email_valido && cpf_valido && telefone_valido) {
            try {
                Connection conexao = null;
                PreparedStatement statement = null;

                String url = "jdbc:mysql://localhost:3306/jota_autopecas";
                String usuario = "root";
                String senha = "";

                conexao = DriverManager.getConnection(url, usuario, senha);

                String sql = "INSERT INTO cliente(nome, email, cpf, data_nasc, telefone) VALUES(?, ?, ?, ?, ?);";
                statement = conexao.prepareStatement(sql);
                statement.setString(1, jfield_nome_cliente.getText());
                statement.setString(2, jfield_email_cliente.getText());
                statement.setString(3, jfield_cpf_cliente.getText());
                statement.setString(4, jfield_data_nascimento.getText());
                statement.setString(5, jfield_telefone_cliente.getText());

                statement.executeUpdate();
                System.out.println("Deu certo aqui.");
            
            } catch (SQLException e) {
                System.out.println("Deu esse erro aqui ô: " + e.getMessage());
            }
        }
        else {
            if (nome_valido == false) {
                JOptionPane.showMessageDialog(null, "NOME INVÁLIDO");
            }
            else if (email_valido == false) {
                JOptionPane.showMessageDialog(null, "EMAIL INVÁLIDO");
            }
            else if (cpf_valido == false) {
                JOptionPane.showMessageDialog(null, "CPF INVÁLIDO");
            }
            else if (telefone_valido == false) {
                JOptionPane.showMessageDialog(null, "TELEFONE INVÁLIDO");
            }
        }
    }//GEN-LAST:event_jbutton_cadastrarActionPerformed

    private void jfield_cpf_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cpf_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cpf_clienteActionPerformed

    private void jfield_data_nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_data_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_data_nascimentoActionPerformed

    private void jfield_email_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_email_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_email_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_cliente().setVisible(true);
            }
        });
    }
    
    // Valida a entrada de acordo com o tamanho do input.
    // num_str = String a ser validada.
    // limite = limite de digitos a ser inserido.
    public static boolean validador_tamanho_texto(String num_str, int limite) {
        boolean tamanho;
        
        // Se o length da String for maior do que o limite, retorna false e o usuário devera digitar novamente.
        if (num_str.length() > limite) {
            tamanho = false;
        }
        else {
            tamanho = true;
        }
        
        System.out.println(tamanho);
        
        return tamanho;
    }
    
    // Valida a entrada de acordo com o tipo de input.
    // num_str = String a ser validada.
    // limite = limite de digitos a ser inserido.
    public static boolean validador_entrada_num(String num_str, int limite) {
        boolean e_num = true;
        
        
        // Se o length da String for maior do que o limite, retorna false e o usuário devera digitar novamente.
        if (num_str.length() != limite) {
            e_num = false;
        }

        // Verifica cada posição da String para saber se é letra ou número.
        // Retorna false se uma posição for letra e acaba com o código, fazendo o usuário escrever denovo.
        // Retorna true se for número e prossegue com o código.
        
        if (e_num == true) {
            for (int i = 0; i < num_str.length(); i++) {
                char c = num_str.charAt(i);
                if ('0' <= c && c <= '9') {
                    e_num = true;
                }
                else {
                    e_num = false;
                    break;
                }
            }
        }

        return e_num;
    }
    
    // Valida a entrada de acordo com o tipo de input.
    // num_str = String a ser validada.
    // limite = limite de digitos a ser inserido.
    public static boolean validador_entrada_str(String num_str, int limite) {
        boolean e_letra;
        
        // Se e_letra for false o código não executa por completo.
        e_letra = validador_tamanho_texto(num_str, limite);
        
        // Verifica cada posição da String para saber se é letra ou número.
        // Retorna true se for letra e prossegue com o código. 
        // Retorna false se for número e para o código, fazendo o usuário digitar novamente.
        
        for (int i = 0; i < num_str.length(); i++) {
            char c = num_str.charAt(i);
            if (('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z')) {
                e_letra = true;
            }
            else {
                e_letra = false;
                break;
            }
        }
        
        return e_letra;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutton_cadastrar;
    private javax.swing.JButton jbutton_sair;
    private javax.swing.JTextField jfield_cpf_cliente;
    private javax.swing.JTextField jfield_data_nascimento;
    private javax.swing.JTextField jfield_email_cliente;
    private javax.swing.JTextField jfield_nome_cliente;
    private javax.swing.JTextField jfield_telefone_cliente;
    private javax.swing.JLabel jlbl_cpf;
    private javax.swing.JLabel jlbl_data_nascimento;
    private javax.swing.JLabel jlbl_email;
    private javax.swing.JLabel jlbl_nome;
    private javax.swing.JLabel jlbl_telefone;
    private javax.swing.JLabel jlbl_title_cadastro_cliente;
    private javax.swing.JPanel jpanel_background;
    // End of variables declaration//GEN-END:variables
}
