/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cadastro_cliente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author kevin
 */
public class Cadastro_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_cliente
     */
    public Cadastro_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_background = new javax.swing.JPanel();
        jlbl_title_cadastro_cliente = new javax.swing.JLabel();
        jlbl_nome = new javax.swing.JLabel();
        jlbl_telefone = new javax.swing.JLabel();
        jlbl_email = new javax.swing.JLabel();
        jfield_nome_cliente = new javax.swing.JTextField();
        jfield_telefone_cliente = new javax.swing.JTextField();
        jfield_email_cliente = new javax.swing.JTextField();
        jbutton_sair = new javax.swing.JButton();
        jbutton_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1036, 612));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_background.setPreferredSize(new java.awt.Dimension(1036, 612));
        jpanel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_title_cadastro_cliente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlbl_title_cadastro_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_title_cadastro_cliente.setText("Cadastro de cliente");
        jpanel_background.add(jlbl_title_cadastro_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jlbl_nome.setText("Nome:");
        jpanel_background.add(jlbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jlbl_telefone.setText("Telefone:");
        jpanel_background.add(jlbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jlbl_email.setText("E-mail:");
        jpanel_background.add(jlbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jpanel_background.add(jfield_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 480, -1));
        jpanel_background.add(jfield_telefone_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 480, -1));
        jpanel_background.add(jfield_email_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 480, -1));

        jbutton_sair.setText("Sair");
        jbutton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_sairActionPerformed(evt);
            }
        });
        jpanel_background.add(jbutton_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jbutton_cadastrar.setText("Cadastrar");
        jbutton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_cadastrarActionPerformed(evt);
            }
        });
        jpanel_background.add(jbutton_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        getContentPane().add(jpanel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_sairActionPerformed

    private void jbutton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_cadastrarActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/jota_autopecas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "INSERT INTO cliente(nome, telefone, email) VALUES(?, ?, ?);";
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jfield_nome_cliente.getText());
            statement.setString(2, jfield_telefone_cliente.getText());
            statement.setString(3, jfield_email_cliente.getText());
            
            statement.executeUpdate();
            System.out.println("Deu certo aqui.");
            
        } catch (SQLException e) {
            System.out.println("Deu esse erro aqui ô: " + e.getMessage());
        }
    }//GEN-LAST:event_jbutton_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutton_cadastrar;
    private javax.swing.JButton jbutton_sair;
    private javax.swing.JTextField jfield_email_cliente;
    private javax.swing.JTextField jfield_nome_cliente;
    private javax.swing.JTextField jfield_telefone_cliente;
    private javax.swing.JLabel jlbl_email;
    private javax.swing.JLabel jlbl_nome;
    private javax.swing.JLabel jlbl_telefone;
    private javax.swing.JLabel jlbl_title_cadastro_cliente;
    private javax.swing.JPanel jpanel_background;
    // End of variables declaration//GEN-END:variables
}
